{"original_code": "def test_mosaic_not_found_error(app):\n    \"\"\"\n    This should probably return a 404 but currently returns a 424 because cogeo_mosaic incorrectly raises a MosaicError\n    instead of MosaicNotFoundError.\n    \"\"\"\n    response = app.get(\"/mosaicjson\", params={\"url\": \"mosaic.json\"})\n    assert response.status_code == 424"}