{"original_code": "async def inner_validation_exception_handler(\n    request: Request, exc: typing.Union[ValidationException, ValidationError]\n):\n    \"\"\"Internal data validation exception.Output a json response and throw the exception again.\"\"\"\n    return make_error_response(\n        status=HTTP_417_EXPECTATION_FAILED,\n        msg=_(\"Internal data validation exception\"),\n        errors=exc.errors(),\n        exc=exc,\n    )"}